### PR TITLE
added clang-cl and updated paths for clang

### PR DESCRIPTION
**Pull request by dmoody256**
I had to change the default env tests, those will never work with clang and msvc style flags

appveyor build with passing clang tests:
https://ci.appveyor.com/project/dmoody256/scons/build/1.0.311
passing travis build:
https://travis-ci.org/dmoody256/scons/builds/342620481

### CODE REVIEW

**Comment by dmoody256** [comment]
build with passing clang tests:
https://ci.appveyor.com/project/dmoody256/scons/build/1.0.309/job/sl28cngrl1j5gg79

**Comment by bdbaddog** [comment]
Does changing to clangcl fix the issue?
I'm not sure we want to introduce that users have to use msvc style flags on win32 for clang, rather than "universal" flags for clang on all platforms.

**Comment by dmoody256** [comment]
Only if you have the clang and MSVC tools together does it use clang-cl. If MSVC is not in the tools then it use gcc stlye clang and adds mingw tools for gcc style clang.

_Sent from my Galaxy Note5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by bdbaddog** [comment]
@dmoody256  - If on windows you don't initialize msvs (or msvc) before using clang, it will fail as it can't find the header files which clang expects to get from elsewhere (msvc, mingw, others?) such as stdio.h and other fundamental c/C++ header files.   So the tool will run, but you won't be able to build anything useful.

**Comment by dmoody256** [comment]
My changes are assuming the user to go one of these two paths on windows:

1. clang with mingw tool for c runtimes and libs
2. clang-cl with MSVC tool c runtimes and libs

If they include MSVC tool, then it goes clang-cl, if not MSVC tool, it goes
clang with mingw.

I don't have any kind of checking for mingw tool from clang, so the case
you describe could happen if they don't manually specify mingw first in the
tool list.

Is there any kind of tool dependency in SCons tool system?

**Comment by bdbaddog** [comment]
On Mon, Feb 19, 2018 at 12:40 PM, Daniel Moody <notifications@github.com>
wrote:

> My changes are assuming the user to go one of these two paths on windows:
>
> 1. clang with mingw tool for c runtimes and libs
> 2. clang-cl with MSVC tool c runtimes and libs
>
> If they include MSVC tool, then it goes clang-cl, if not MSVC tool, it goes
> clang with mingw.
>
> I don't have any kind of checking for mingw tool from clang, so the case
> you describe could happen if they don't manually specify mingw first in the
> tool list.
>
> Is there any kind of tool dependency in SCons tool system?
>

Not yet. Probably worth bringing this discussion to the users or dev
mailing list.
Gary was working on a rewrite of toolchains and platform logic.

Basically the idea was you'd specify a tool chain and it would only config
if all the tools needed were available and would allow specifying multiple
sets of tools which could fullfil that toolchain.

Still a WIP, I'm not sure how far along it is.

I'm going to bring a "how do you use clang and SCons" thread to users
mailing list to gather some data on how people use it.

I believe (and I could be wrong) that if you're using clang on windows,
you're probably doing multi-platform development and wouldn't want to deal
with MSVC vs "standard" posix/linux/unix compiler flags.

**Comment by dmoody256** [comment]
my other thought was make clang-cl a separate tool from clang

**Comment by bdbaddog** [comment]
That's not a bad idea!
mingw accepts -o and not the msvc style args right?

**Comment by dmoody256** [comment]
yes, mingw accepts the gcc style flags.

so for the clang tool, it can link with MSVC runtime or mingw runtime on windows. Currently the path with MSVC linking is broken I believe because the msvc tool will change the way the compiler flags are printed and clang errors out thinking the / is indicating files.

so we need to 
1. fix clang tool to setup an MSVC environment without changing the compiler flag style
2. make a new clang-cl tool which uses msvc tool and msvc compiler flags

**Comment by bdbaddog** [comment]
If you use "msvs" instead of 'msvc', then clang will work as expected..
It set's up the needed shell variables without changing the compile line
flags.

-Bill

**Comment by bdbaddog** [comment]
I'm going to close this pull request.
I think we decided clang-cl would be a separate tool.
I think it's important that if a user specifies clang they get clang which should handle the same style of arguments regardless of platform. Otherwise they could expect "normal" compiler args and get clang-cl, or expect MS compiler flags and get clang on linux.

**Comment by dmoody256** [comment]
Making a reference to the real issue on the SCons project repo
https://github.com/SCons/scons/pull/3052

**Pull request closed without merging**
